# Generated by Django 3.0.8 on 2020-12-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='cpf'),
        ),
    ]
